### ISSUE TITLE
TypeError when silver.py is executed outside Silver directory.

### ISSUE THREAD

**Issue by llazzaro** [s0md3v/Silver#7]
Hi,

I was trying to call silver.py outside the directory and I got the following error:

```
fagent@faradayagent:~$ /home/fagent/Silver/silver.py
Traceback (most recent call last):
  File "/home/fagent/Silver/silver.py", line 13, in <module>
    from modules.shodan import shodan
  File "/home/fagent/Silver/modules/shodan.py", line 5, in <module>
    from modules.vulners import vulners, cache
  File "/home/fagent/Silver/modules/vulners.py", line 7, in <module>
    database = json.loads(reader(file))
  File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'bool'
```

Will you like to create a python package of silver? I think the root of this problem could be fixed by creating a package (I could help with this).

Thanks!

**Comment by s0md3v** [comment]
This error is actually caused when Silver is run without any arguments, this will be handled in the next release.
